/**
 * Catálogo por defecto de especialidades. Misma fuente que el frontend web.
 */
export const DEFAULT_SPECIALTIES: string[] = [
  'Medicina general',
  'Medicina familiar',
  'Medicina interna',
  'Medicina del trabajo',
  'Medicina del deporte',
  'Pediatría',
  'Neonatología',
  'Ginecología y obstetricia',
  'Medicina reproductiva',
  'Cardiología',
  'Cirugía cardiovascular',
  'Hemodinamia',
  'Dermatología',
  'Dermatología pediátrica',
  'Endocrinología',
  'Diabetología',
  'Nutrición clínica',
  'Gastroenterología',
  'Hepatología',
  'Coloproctología',
  'Neumología',
  'Otorrinolaringología',
  'Neurología',
  'Neurocirugía',
  'Psiquiatría',
  'Psicología',
  'Neuropsicología',
  'Nefrología',
  'Urología',
  'Oncología clínica',
  'Hematología',
  'Radioterapia oncológica',
  'Traumatología y ortopedia',
  'Reumatología',
  'Fisiatría',
  'Oftalmología',
  'Cirugía general',
  'Cirugía plástica',
  'Cirugía vascular',
  'Cirugía pediátrica',
  'Cirugía maxilofacial',
  'Radiología',
  'Patología',
  'Medicina nuclear',
  'Anestesiología',
  'Geriatría',
  'Infectología',
  'Alergología e inmunología',
  'Medicina paliativa',
  'Genética médica',
  'Odontología general',
  'Ortodoncia',
  'Endodoncia',
  'Periodoncia',
  'Implantología dental',
  'Fisioterapia',
  'Kinesiología',
  'Fonoaudiología',
  'Terapia ocupacional',
  'Optometría',
  'Nutricionista',
  'Coaching nutricional',
];
